### ISSUE TITLE
yarn build ができない

### ISSUE THREAD

**Issue by habara-k** [git-deck/git-deck#148]
```
 FATAL  Nuxt build error                                                                                                                                                                          16:51:11

  at WebpackBundler.webpackCompile (/usr/local/share/.config/yarn/global/node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async WebpackBundler.build (/usr/local/share/.config/yarn/global/node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (/usr/local/share/.config/yarn/global/node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Generator.initiate (/usr/local/share/.config/yarn/global/node_modules/@nuxt/generator/dist/generator.js:110:7)
  at async Generator.generate (/usr/local/share/.config/yarn/global/node_modules/@nuxt/generator/dist/generator.js:71:5)
  at async Object.run (/usr/local/share/.config/yarn/global/node_modules/@nuxt/cli/dist/cli-build.js:106:7)
  at async NuxtCommand.run (/usr/local/share/.config/yarn/global/node_modules/@nuxt/cli/dist/cli-index.js:413:7)
```

**Comment by habara-k** [comment]
現状Errorが生じている状態で`yarn dev`を動かしていたので、まずエラーを除く
